[package]
name = "pinhole-client"
version = "0.1.0"
authors = ["Michael Melanson <michael@michaelmelanson.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinhole-protocol = { path = "../pinhole-protocol" }
async-std = "1.5"
crossbeam = "0.7"
glium = { version = "0.26", default-features = true }
image = "0.23"
imgui = "*"
imgui-glium-renderer = "*"
imgui-winit-support = "*"
url = "2.1"
